---
# default policies
# `ufw enable`
- ufw: state=enabled
# `ufw default deny`
- ufw: policy=deny
# `ufw default reject outgoing`
- ufw: direction=outgoing policy=reject

# minimum ports
# `ufw allow out 53` (DNS)
- ufw: rule=allow direction=out to_port=53
# `ufw allow out 80/tcp` (http)
- ufw: rule=allow direction=out to_port=80 proto=tcp
# `ufw allow out 443/tcp` (https)
- ufw: rule=allow direction=out to_port=443 proto=tcp
# `ufw allow out 123/udp` (ntp)
- ufw: rule=allow direction=out to_port=123 proto=udp

# `ufw limit 22/tcp` (ssh)
- ufw: rule=limit to_port=22 proto=tcp

# ircs
- ufw: rule=limit to_port=6697 proto=tcp

# http,https
- ufw: rule=reject to_port=80,443 proto=tcp

# ignore attacks
- ufw: rule=deny to_port=23 proto=tcp # telnet
- ufw: rule=deny to_port=1080 proto=tcp # proxy
- ufw: rule=deny to_port=1433 proto=tcp # SQL Server
- ufw: rule=deny to_port=3128 proto=tcp # proxy
- ufw: rule=deny to_port=3306 proto=tcp # mysql
- ufw: rule=deny to_port=3389 proto=tcp # RDP
- ufw: rule=deny to_port=8000 proto=tcp # proxy
- ufw: rule=deny to_port=5901 proto=tcp # VNC
- ufw: rule=deny to_port=8080 proto=tcp # proxy
