---
- hosts: all
  sudo: yes
  roles:
  - { role: znzj.ja_jp, ja_jp_enable_backports: yes }
  - znzj.grub
  - firewall
  - ufw
  - znzj.github-users
  - znzj.ngircd
  - misc
  - znzj.rbenv
  - znzj.nadoka
