---
- lineinfile: 'dest=/etc/hosts.deny line="ALL: ALL"'
- lineinfile: 'dest=/etc/hosts.allow line="sshd: 127.0.0.1 [::1]"'
- lineinfile: 'dest=/etc/hosts.allow line="sshd: 10."'
- lineinfile: 'dest=/etc/hosts.allow line="sshd: .jp"'
